cmake_minimum_required(VERSION 3.22)

if(NOT DEFINED CC1 OR NOT DEFINED OUTPUT_DIR)
  message(FATAL_ERROR "Use -DCC1=<executable> -DOUTPUT_DIR=<artifact directory>")
endif()
get_filename_component(PROJECT_DIR "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
get_filename_component(CC1 "${CC1}" ABSOLUTE BASE_DIR "${PROJECT_DIR}")
get_filename_component(OUTPUT_DIR "${OUTPUT_DIR}" ABSOLUTE BASE_DIR "${PROJECT_DIR}")
file(MAKE_DIRECTORY "${OUTPUT_DIR}")
file(GLOB_RECURSE SOURCES "${CMAKE_CURRENT_LIST_DIR}/*.c")
list(SORT SOURCES)

set(REPORT "# AST dump audit\n\nCommand: `cc1 --dump-ast -fno-color-diagnostics <file>`.\n\n")
string(APPEND REPORT "Exit status 0 means the parser accepted the syntax, not that the AST is complete.\n\n")
string(APPEND REPORT "| File | Exit status | UnsupportedNode | Verification |\n|---|---|---:|---|\n")
set(DETAILS "")
set(COUNT 0)
set(ACCEPTED 0)
set(REJECTED 0)
set(ABNORMAL 0)
set(INCOMPLETE 0)
set(GOLDEN_MATCHES 0)

foreach(SOURCE IN LISTS SOURCES)
  file(RELATIVE_PATH RELATIVE "${CMAKE_CURRENT_LIST_DIR}" "${SOURCE}")
  string(REGEX REPLACE "\\.c$" "" STEM "${RELATIVE}")
  get_filename_component(PARENT "${OUTPUT_DIR}/${STEM}.ast" DIRECTORY)
  file(MAKE_DIRECTORY "${PARENT}")
  execute_process(
    COMMAND "${CC1}" --dump-ast -fno-color-diagnostics "Tests/${RELATIVE}"
    WORKING_DIRECTORY "${PROJECT_DIR}"
    RESULT_VARIABLE STATUS
    OUTPUT_VARIABLE AST
    ERROR_VARIABLE DIAGNOSTIC
    TIMEOUT 3
  )
  file(WRITE "${OUTPUT_DIR}/${STEM}.ast" "${AST}")
  file(WRITE "${OUTPUT_DIR}/${STEM}.stderr" "${DIAGNOSTIC}")
  file(WRITE "${OUTPUT_DIR}/${STEM}.status" "${STATUS}\n")
  string(REGEX MATCHALL "UnsupportedNode" MISSING "${AST}")
  list(LENGTH MISSING MISSING_COUNT)

  if("${STATUS}" STREQUAL "0")
    math(EXPR ACCEPTED "${ACCEPTED} + 1")
    set(VERDICT "AST printed; requires inspection")
    if(MISSING_COUNT GREATER 0)
      math(EXPR INCOMPLETE "${INCOMPLETE} + 1")
      set(VERDICT "Incomplete dump")
    endif()
    if(EXISTS "${CMAKE_CURRENT_LIST_DIR}/${STEM}.ast")
      file(READ "${CMAKE_CURRENT_LIST_DIR}/${STEM}.ast" EXPECTED)
      if("${AST}" STREQUAL "${EXPECTED}")
        math(EXPR GOLDEN_MATCHES "${GOLDEN_MATCHES} + 1")
        set(VERDICT "Matches expected dump")
      else()
        set(VERDICT "ERROR: dump differs from expected output")
      endif()
    endif()
    if(NOT "${DIAGNOSTIC}" STREQUAL "")
      set(VERDICT "ERROR: diagnostics with exit status 0")
    endif()
  elseif("${STATUS}" STREQUAL "1")
    math(EXPR REJECTED "${REJECTED} + 1")
    if(RELATIVE MATCHES "(^|/)invalid_")
      set(VERDICT "Expected syntax/lexical error")
    else()
      set(VERDICT "Unsupported C syntax or bug")
    endif()
    if(NOT "${AST}" STREQUAL "")
      set(VERDICT "ERROR: AST printed despite an error")
    endif()
  else()
    math(EXPR ABNORMAL "${ABNORMAL} + 1")
    set(VERDICT "ERROR: crash or timeout")
  endif()

  math(EXPR COUNT "${COUNT} + 1")
  string(APPEND REPORT "| [Tests/${RELATIVE}](${STEM}.ast) | ${STATUS} | ${MISSING_COUNT} | ${VERDICT} |\n")
  string(APPEND DETAILS "\n## Tests/${RELATIVE}\n\nExit status: `${STATUS}`. ${VERDICT}.\n\n")
  if(NOT "${AST}" STREQUAL "")
    string(APPEND DETAILS "```text\n${AST}```\n\n")
  endif()
  if(NOT "${DIAGNOSTIC}" STREQUAL "")
    string(APPEND DETAILS "```text\n${DIAGNOSTIC}```\n\n")
  endif()
  string(APPEND DETAILS "[AST](${STEM}.ast) / [stderr](${STEM}.stderr) / [status](${STEM}.status)\n")
  message(STATUS "Tests/${RELATIVE}: ${STATUS}, ${VERDICT}")
endforeach()

string(APPEND REPORT "\n${COUNT} files examined: ${ACCEPTED} accepted, ${REJECTED} rejected with exit status 1, ${ABNORMAL} crash/timeout.\n")
string(APPEND REPORT "${GOLDEN_MATCHES} dumps match the expected text; ${INCOMPLETE} accepted files contain UnsupportedNode.\n")
string(APPEND REPORT "The structural tests in parser_tests are still required to detect missing data or incorrect trees.\n${DETAILS}")
file(WRITE "${OUTPUT_DIR}/report.md" "${REPORT}")
message(STATUS "Report: ${OUTPUT_DIR}/report.md")
message(STATUS "Summary: ${COUNT} files, ${ACCEPTED} accepted, ${REJECTED} rejected, ${ABNORMAL} crash/timeout, ${INCOMPLETE} incomplete dumps")
