cmake_minimum_required(VERSION 3.22)
file(MAKE_DIRECTORY "${SCRATCH_DIR}")

function(run_case expected_status)
  execute_process(COMMAND "${CC1}" -fno-color-diagnostics ${ARGN}
    RESULT_VARIABLE STATUS OUTPUT_VARIABLE OUTPUT ERROR_VARIABLE DIAGNOSTIC TIMEOUT 4)
  if(NOT "${STATUS}" STREQUAL "${expected_status}")
    message(FATAL_ERROR "Expected status ${expected_status}, got ${STATUS}: ${ARGN}\n${DIAGNOSTIC}")
  endif()
  set(OUTPUT "${OUTPUT}" PARENT_SCOPE)
  set(DIAGNOSTIC "${DIAGNOSTIC}" PARENT_SCOPE)
endfunction()

file(WRITE "${SCRATCH_DIR}/valid.c" "#define ADD(x, y) ((x) + (y))\ndouble f(short x, float y) { return ADD(x, y); }\n")
run_case(0 "${SCRATCH_DIR}/valid.c")
if(NOT "${OUTPUT}" STREQUAL "" OR NOT "${DIAGNOSTIC}" STREQUAL "")
  message(FATAL_ERROR "Successful semantic analysis emitted output")
endif()
run_case(0 --dump-sema "${SCRATCH_DIR}/valid.c")
if(NOT "${OUTPUT}" MATCHES "ImplicitCastExpr arithmetic" OR
   NOT "${OUTPUT}" MATCHES "ImplicitCastExpr lvalue-to-rvalue" OR
   NOT "${OUTPUT}" MATCHES "\\[short, lvalue\\] IdentExpr x" OR
   "${OUTPUT}" MATCHES "<untyped>" OR NOT "${DIAGNOSTIC}" STREQUAL "")
  message(FATAL_ERROR "Incorrect typed AST:\n${OUTPUT}\n${DIAGNOSTIC}")
endif()

file(WRITE "${SCRATCH_DIR}/invalid.c" "int f(void) { return missing + 1; }\n")
foreach(MODE IN ITEMS check dump)
  set(OPTION)
  if(MODE STREQUAL "dump")
    set(OPTION --dump-sema)
  endif()
  run_case(1 ${OPTION} "${SCRATCH_DIR}/invalid.c")
  if(NOT "${OUTPUT}" STREQUAL "" OR NOT "${DIAGNOSTIC}" MATCHES "1:22: error: use of undeclared identifier 'missing'")
    message(FATAL_ERROR "Incorrect semantic failure:\n${OUTPUT}\n${DIAGNOSTIC}")
  endif()
endforeach()
run_case(0 --dump-ast "${SCRATCH_DIR}/invalid.c")
if(NOT "${OUTPUT}" MATCHES "IdentExpr missing" OR NOT "${DIAGNOSTIC}" STREQUAL "")
  message(FATAL_ERROR "Syntax-only dump ran semantic analysis")
endif()
run_case(0 -E "${SCRATCH_DIR}/invalid.c")
run_case(0 --dump-tokens "${SCRATCH_DIR}/invalid.c")

file(WRITE "${SCRATCH_DIR}/bad.h" "int header(void) { return missing; }\n")
file(WRITE "${SCRATCH_DIR}/include.c" "#include \"bad.h\"\n")
run_case(1 --dump-sema "${SCRATCH_DIR}/include.c")
string(FIND "${DIAGNOSTIC}" "${SCRATCH_DIR}/bad.h:1:27: error: use of undeclared identifier 'missing'" POSITION)
if(NOT "${OUTPUT}" STREQUAL "" OR POSITION EQUAL -1 OR NOT "${DIAGNOSTIC}" MATCHES "\\^")
  message(FATAL_ERROR "Semantic diagnostic lost header location:\n${DIAGNOSTIC}")
endif()

file(WRITE "${SCRATCH_DIR}/macro.c" "#define VALUE missing\nint f(void) { return VALUE; }\n")
run_case(1 "${SCRATCH_DIR}/macro.c")
if(NOT "${DIAGNOSTIC}" MATCHES "2:22: error: use of undeclared identifier 'missing'")
  message(FATAL_ERROR "Semantic diagnostic lost macro invocation location:\n${DIAGNOSTIC}")
endif()

run_case(1 --dump-sema --dump-ast "${SCRATCH_DIR}/valid.c")
run_case(1 --dump-sema --dump-tokens "${SCRATCH_DIR}/valid.c")
run_case(1 -E --dump-sema "${SCRATCH_DIR}/valid.c")
