cmake_minimum_required(VERSION 3.22)
file(MAKE_DIRECTORY "${SCRATCH_DIR}")

function(run_case expected_status)
  execute_process(
    COMMAND "${CC1}" -fno-color-diagnostics ${ARGN}
    RESULT_VARIABLE STATUS OUTPUT_VARIABLE OUTPUT ERROR_VARIABLE DIAGNOSTIC
    TIMEOUT 4
  )
  if(NOT "${STATUS}" STREQUAL "${expected_status}")
    message(FATAL_ERROR "Expected status ${expected_status}, got ${STATUS}: ${ARGN}\n${DIAGNOSTIC}")
  endif()
  set(OUTPUT "${OUTPUT}" PARENT_SCOPE)
  set(DIAGNOSTIC "${DIAGNOSTIC}" PARENT_SCOPE)
endfunction()

run_case(0 "${TEST_DIR}/program.c")
if(NOT "${OUTPUT}" STREQUAL "" OR NOT "${DIAGNOSTIC}" STREQUAL "")
  message(FATAL_ERROR "Default parsing emitted output: ${OUTPUT}\n${DIAGNOSTIC}")
endif()
run_case(0 -E "${TEST_DIR}/program.c")
set(EXPECTED "int header_value ;\nint nested_value ;\nint once_value ;\nint main ( void ) {\nreturn 6 + 1 ;\n}\n")
if(NOT "${OUTPUT}" STREQUAL EXPECTED OR NOT "${DIAGNOSTIC}" STREQUAL "")
  message(FATAL_ERROR "Incorrect preprocessed output:\n${OUTPUT}\n${DIAGNOSTIC}")
endif()

file(WRITE "${SCRATCH_DIR}/angle.c" "#include <library.h>\nint main(void) { return LIB_VALUE; }\n")
run_case(0 "-I${TEST_DIR}/search" "${SCRATCH_DIR}/angle.c")
run_case(0 -I "${TEST_DIR}/search" --dump-ast "${SCRATCH_DIR}/angle.c")
if(NOT "${OUTPUT}" MATCHES "VarDecl library_value" OR NOT "${OUTPUT}" MATCHES "IntLitExpr 9")
  message(FATAL_ERROR "Include path did not reach the parser:\n${OUTPUT}")
endif()

file(WRITE "${SCRATCH_DIR}/syntax.c" "int main(void) { int value = ; }\n")
run_case(0 -E "${SCRATCH_DIR}/syntax.c")
run_case(1 "${SCRATCH_DIR}/syntax.c")
if(NOT "${OUTPUT}" STREQUAL "")
  message(FATAL_ERROR "AST was printed after a parse error")
endif()

file(WRITE "${SCRATCH_DIR}/missing.c" "#include \"absent-test-header.h\"\n")
foreach(MODE IN ITEMS parse preprocess ast)
  set(OPTION)
  if(MODE STREQUAL "preprocess")
    set(OPTION -E)
  elseif(MODE STREQUAL "ast")
    set(OPTION --dump-ast)
  endif()
  run_case(1 ${OPTION} "${SCRATCH_DIR}/missing.c")
  if(NOT "${OUTPUT}" STREQUAL "" OR NOT "${DIAGNOSTIC}" MATCHES "1:1: error: include file 'absent-test-header.h' not found")
    message(FATAL_ERROR "Incorrect missing-include diagnostic:\n${OUTPUT}\n${DIAGNOSTIC}")
  endif()
endforeach()

foreach(KIND IN ITEMS lexical syntax)
  file(WRITE "${SCRATCH_DIR}/header_${KIND}.c" "#include \"${TEST_DIR}/include/invalid_${KIND}.h\"\n")
  run_case(1 --dump-ast "${SCRATCH_DIR}/header_${KIND}.c")
  if(KIND STREQUAL "lexical")
    set(HEADER "${TEST_DIR}/include/invalid_lexical.h:1:5: error: unknown character")
    set(EXCERPT "    1 | int @;\n      |     ^\n")
  else()
    set(HEADER "${TEST_DIR}/include/invalid_syntax.h:2:1: error: expected ';' after return")
    set(EXCERPT "    2 | }\n      | ^\n")
  endif()
  string(FIND "${DIAGNOSTIC}" "${HEADER}" HEADER_POSITION)
  string(FIND "${DIAGNOSTIC}" "${EXCERPT}" EXCERPT_POSITION)
  string(REGEX MATCHALL "error:" ERRORS "${DIAGNOSTIC}")
  list(LENGTH ERRORS ERROR_COUNT)
  if(NOT "${OUTPUT}" STREQUAL "" OR HEADER_POSITION EQUAL -1 OR EXCERPT_POSITION EQUAL -1 OR NOT ERROR_COUNT EQUAL 1)
    message(FATAL_ERROR "Incorrect header diagnostic:\n${DIAGNOSTIC}")
  endif()
endforeach()

run_case(1 -E --dump-ast "${TEST_DIR}/program.c")
run_case(1 -I)

run_case(0 "${TEST_DIR}/macros.c")
run_case(0 -E "${TEST_DIR}/macros.c")
if(NOT "${OUTPUT}" MATCHES "int macro \\( int value \\)" OR
   NOT "${OUTPUT}" MATCHES "return 18 ;" OR NOT "${DIAGNOSTIC}" STREQUAL "")
  message(FATAL_ERROR "Function macros did not reach the CLI:\n${OUTPUT}\n${DIAGNOSTIC}")
endif()

file(WRITE "${SCRATCH_DIR}/macro_error.c" "#define CAT(a,b) a ## b\nint CAT(name,+);\n")
foreach(MODE IN ITEMS parse preprocess ast)
  set(OPTION)
  if(MODE STREQUAL "preprocess")
    set(OPTION -E)
  elseif(MODE STREQUAL "ast")
    set(OPTION --dump-ast)
  endif()
  run_case(1 ${OPTION} "${SCRATCH_DIR}/macro_error.c")
  string(REGEX MATCHALL "error:" ERRORS "${DIAGNOSTIC}")
  list(LENGTH ERRORS ERROR_COUNT)
  if(NOT "${OUTPUT}" STREQUAL "" OR NOT ERROR_COUNT EQUAL 1 OR
     NOT "${DIAGNOSTIC}" MATCHES "2:5: error: token paste does not form one preprocessing token")
    message(FATAL_ERROR "Incorrect macro diagnostic:\n${OUTPUT}\n${DIAGNOSTIC}")
  endif()
endforeach()
