#include "Token.hpp"

const char *tokenKindName(TokenKind k) {
  switch (k) {
  case TokenKind::INT_LIT:
    return "INT_LIT";
  case TokenKind::FLOAT_LIT:
    return "FLOAT_LIT";
  case TokenKind::CHAR_LIT:
    return "CHAR_LIT";
  case TokenKind::STRING_LIT:
    return "STRING_LIT";

  case TokenKind::IDENT:
    return "IDENT";

  case TokenKind::KW_AUTO:
    return "KW_AUTO";
  case TokenKind::KW_BREAK:
    return "KW_BREAK";
  case TokenKind::KW_CASE:
    return "KW_CASE";
  case TokenKind::KW_CHAR:
    return "KW_CHAR";
  case TokenKind::KW_CONST:
    return "KW_CONST";
  case TokenKind::KW_CONTINUE:
    return "KW_CONTINUE";
  case TokenKind::KW_DEFAULT:
    return "KW_DEFAULT";
  case TokenKind::KW_DO:
    return "KW_DO";
  case TokenKind::KW_DOUBLE:
    return "KW_DOUBLE";
  case TokenKind::KW_ELSE:
    return "KW_ELSE";
  case TokenKind::KW_ENUM:
    return "KW_ENUM";
  case TokenKind::KW_EXTERN:
    return "KW_EXTERN";
  case TokenKind::KW_FLOAT:
    return "KW_FLOAT";
  case TokenKind::KW_FOR:
    return "KW_FOR";
  case TokenKind::KW_GOTO:
    return "KW_GOTO";
  case TokenKind::KW_IF:
    return "KW_IF";
  case TokenKind::KW_INT:
    return "KW_INT";
  case TokenKind::KW_LONG:
    return "KW_LONG";
  case TokenKind::KW_REGISTER:
    return "KW_REGISTER";
  case TokenKind::KW_RETURN:
    return "KW_RETURN";
  case TokenKind::KW_SHORT:
    return "KW_SHORT";
  case TokenKind::KW_SIGNED:
    return "KW_SIGNED";
  case TokenKind::KW_SIZEOF:
    return "KW_SIZEOF";
  case TokenKind::KW_STATIC:
    return "KW_STATIC";
  case TokenKind::KW_STRUCT:
    return "KW_STRUCT";
  case TokenKind::KW_SWITCH:
    return "KW_SWITCH";
  case TokenKind::KW_TYPEDEF:
    return "KW_TYPEDEF";
  case TokenKind::KW_UNION:
    return "KW_UNION";
  case TokenKind::KW_UNSIGNED:
    return "KW_UNSIGNED";
  case TokenKind::KW_VOID:
    return "KW_VOID";
  case TokenKind::KW_VOLATILE:
    return "KW_VOLATILE";
  case TokenKind::KW_WHILE:
    return "KW_WHILE";

  case TokenKind::L_PAREN:
    return "L_PAREN";
  case TokenKind::R_PAREN:
    return "R_PAREN";
  case TokenKind::L_BRACE:
    return "L_BRACE";
  case TokenKind::R_BRACE:
    return "R_BRACE";
  case TokenKind::L_BRACKET:
    return "L_BRACKET";
  case TokenKind::R_BRACKET:
    return "R_BRACKET";
  case TokenKind::SEMICOLON:
    return "SEMICOLON";
  case TokenKind::COLON:
    return "COLON";
  case TokenKind::COMMA:
    return "COMMA";
  case TokenKind::DOT:
    return "DOT";
  case TokenKind::HASH:
    return "HASH";
  case TokenKind::HASHHASH:
    return "HASHHASH";
  case TokenKind::ARROW:
    return "ARROW";
  case TokenKind::ELLIPSIS:
    return "ELLIPSIS";

  case TokenKind::PLUS:
    return "PLUS";
  case TokenKind::MINUS:
    return "MINUS";
  case TokenKind::MUL:
    return "MUL";
  case TokenKind::DIV:
    return "DIV";
  case TokenKind::MOD:
    return "MOD";
  case TokenKind::AMP:
    return "AMP";
  case TokenKind::PIPE:
    return "PIPE";
  case TokenKind::CARET:
    return "CARET";
  case TokenKind::TILDE:
    return "TILDE";
  case TokenKind::LSHIFT:
    return "LSHIFT";
  case TokenKind::RSHIFT:
    return "RSHIFT";
  case TokenKind::BANG:
    return "BANG";
  case TokenKind::AMPAMP:
    return "AMPAMP";
  case TokenKind::PIPEPIPE:
    return "PIPEPIPE";
  case TokenKind::EQ:
    return "EQ";
  case TokenKind::NEQ:
    return "NEQ";
  case TokenKind::LT:
    return "LT";
  case TokenKind::GT:
    return "GT";
  case TokenKind::LEQ:
    return "LEQ";
  case TokenKind::GEQ:
    return "GEQ";
  case TokenKind::ASSIGN:
    return "ASSIGN";
  case TokenKind::PLUS_ASSIGN:
    return "PLUS_ASSIGN";
  case TokenKind::MINUS_ASSIGN:
    return "MINUS_ASSIGN";
  case TokenKind::MUL_ASSIGN:
    return "MUL_ASSIGN";
  case TokenKind::DIV_ASSIGN:
    return "DIV_ASSIGN";
  case TokenKind::MOD_ASSIGN:
    return "MOD_ASSIGN";
  case TokenKind::AMP_ASSIGN:
    return "AMP_ASSIGN";
  case TokenKind::PIPE_ASSIGN:
    return "PIPE_ASSIGN";
  case TokenKind::CARET_ASSIGN:
    return "CARET_ASSIGN";
  case TokenKind::LSHIFT_ASSIGN:
    return "LSHIFT_ASSIGN";
  case TokenKind::RSHIFT_ASSIGN:
    return "RSHIFT_ASSIGN";
  case TokenKind::PLUSPLUS:
    return "PLUSPLUS";
  case TokenKind::MINUSMINUS:
    return "MINUSMINUS";
  case TokenKind::QUESTION:
    return "QUESTION";

  case TokenKind::END_OF_FILE:
    return "END_OF_FILE";
  case TokenKind::ERROR:
    return "ERROR";

  default:
    return "UNKNOWN";
  }
}
